events {}

http {
    server {
        listen 80;

        # Strip trailing slashes internally to fix cached 301 redirects
        rewrite ^/(.*)/$ /$1 last;

        # Frontend
        location / {
            proxy_pass http://frontend:80;
        }

        # APIs
        location /api/users {
            proxy_pass http://user-service:8080/api/users;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api/products {
            proxy_pass http://product-service:8080/api/products;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api/orders {
            proxy_pass http://order-service:8080/api/orders;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /users/actuator/health {
            proxy_pass http://user-service:8080/actuator/health;            
        }

        location /products/actuator/health {
            proxy_pass http://product-service:8080/actuator/health;            
        }

        location /orders/actuator/health {
            proxy_pass http://order-service:8080/actuator/health;            
        }
    }
}



# Problem	Result
# Wrong IP	Logs show container IP
# Wrong protocol	HTTPS redirect issues
# Missing host	Routing/auth fails
# No HTTP/1.1	Connection issues

# To forward original client request information like IP, host, and protocol to backend services when using a reverse proxy.